app/user/__init__.py
# usr/bin/env/python3
# -*- coding=utf-8 -*-
# time: 
# __author__ = Aidan
from flask import Blueprint
blueprint = Blueprint('user', __name__, template_folder='templates')
from . import routes
from . import user_forms

app/user/routes.py
# usr/bin/env/python3
# -*- coding=utf-8 -*-
# time: 
# __author__ = Aidan
from flask import url_for, render_template, redirect, g, request, session
from . import blueprint
from models.model import UserInfo, db, gen_id, BlogInfo
from .user_forms import UserForm


@blueprint.route('/')
@blueprint.route('/index')
def index():
    if g.uid:
        uid = g.uid
        user_info = UserInfo.query.filter(UserInfo.id == uid).first()
        user_name = user_info.net_name
        blog_info = BlogInfo.query.filter(BlogInfo.id == uid).first()
        admin_name = '站长'
        # return render_template('tourist_index.html', name=user_name, speciality=blog_info.speciality,
        #                        personal_signature=blog_info.personal_signature,
        #                        personal_profile=blog_info.personal_peofile,
        #                        personal_expectation=blog_info.personal_expectation)
        return render_template('tourist_index.html', **locals())
    else:
        return redirect(url_for('user.log_in'))
        # return redirect('login')


@blueprint.route('/login')
def log_in():
    return render_template('login.html')


@blueprint.route('/login/success', methods=["GET", "POST"])
def log_in_success():
    # 登陆的接口为POST
    if request.method == "POST":
        if request.form.get('user_name'):
            return "error"  # TODO
        else:
            uem = request.form.get('email', None)
            user = UserInfo.query.filter(UserInfo.user == uem).first()
            if user:
                uid = user.id
                session['uid'] = uid
                upw = request.form.get('password', None)
                if user.pwd == upw:
                    user_info = UserInfo.query.filter(UserInfo.id == uid).first()
                    user_name = user_info.net_name
                    blog_info = BlogInfo.query.filter(BlogInfo.id == uid).first()
                    admin_name = '站长'
                    return render_template('index.html', **locals())
                else:
                    return "密码错误"  # TODO
            else:
                return render_template('login.html')
    # 注册的接口为GET
    elif request.method == "GET":
        if request.args.get('user_name'):
            uid = gen_id()
            uem = request.args.get('email')
            upw = request.args.get('password')
            net_name = request.args.get('user_name')
            new_user_info = UserInfo()
            new_user_info.id = uid
            new_user_info.user = uem
            new_user_info.pwd = upw
            new_user_info.net_name = net_name
            db.session.add(new_user_info)
            db.session.commit()
            session['uid'] = uid
            return redirect(url_for('user.user_form'))
        else:
            return "error"  # TODO
    else:
        return "请求方式错误"  # TODO


# 用户填写基本信息
@blueprint.route('/user_form', methods=["GET", "POST"])
def user_form():
    if g.uid:
        if request.method == "GET":
            form = UserForm()
            return render_template('user_form.html', forms=form)
        form = UserForm()
        # request.method==' post '  and  from.validate() = form.validate_on_submit()
        if form.validate():
            print([i.data for i in form])
            return "验证成功"
            blog_info_list_one = []
            for i in form:
                blog_info_list_one.append(i.data)
            blog_info_list = blog_info_list_one[:-1]
            blog_info = BlogInfo()
            blog_info.id = g.uid
            blog_info.sex = blog_info_list[0]
            blog_info.phone = blog_info_list[1]
            blog_info.qq = blog_info_list[2]
            blog_info.wx = blog_info_list[3]
            blog_info.speciality = blog_info_list[4]
            blog_info.personal_signature = blog_info_list[5]
            blog_info.personal_profile = blog_info_list[6]
            blog_info.personal_expectation = blog_info_list[7]
            blog_info.status = 0
            db.session.add(blog_info)
            db.session.commit()
            return redirect(url_for('user.index'))
        else:
            return render_template('user_form.html', forms=form)
    else:
        return redirect(url_for('user.log_in'))

app/user/templates/index.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>{{ user_name }}的博客</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css') }}" />
		<noscript><link rel="stylesheet" href="{{ url_for('static', filename='assets/css/noscript.css') }}" charset="utf-8"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="logo">
							<span class="icon fa-gem"></span>
						</div>
						<div class="content">
							<div class="inner">
								<h1>{{ user_name }}的博客</h1>
								<p>{{ blog_info.personal_signature }}</p>
							</div>
						</div>
						<nav>
							<ul>
								<li><a href="#intro">简介</a></li>
								<li><a href="#work">随笔</a></li>
<!--								<li><a href="#about">{{ speciality }}</a></li>-->
								<li><a href="#about">{{ blog_info.speciality }}</a></li>
								<li><a href="#contact">联系{{ admin_name }}</a></li>
								<!--<li><a href="#elements">Elements</a></li>-->
							</ul>
						</nav>
					</header>

				<!-- Main -->
					<div id="main">

						<!-- Intro -->
							<article id="intro">
								<h2 class="major">简介</h2>
								<span class="image main"><img src="{{url_for('static', filename='images/pic01.jpg')}}" alt="" /></span>
								<p>{{ blog_info.personal_profile }}</p>
								<p>{{ blog_info.personal_expectation }}</p>
								<p> <a href="#work">随笔介绍</a></p>
							</article>

						<!-- Work -->
							<article id="work">
								<h2 class="major">随笔</h2>
								<span class="image main"><img src="{{url_for('static', filename='images/pic02.jpg')}}" alt="" /></span>
								<p>此处的文章列表正在制作当中</p>
							</article>

						<!-- About -->
							<article id="about">
								<h2 class="major">{{ blog_info.speciality }}</h2>
								<span class="image main"><img src="{{url_for('static', filename='images/pic03.jpg')}}"alt="" /></span>
								<p>此处为专栏作品，正在制作中</p>
							</article>

						<!-- Contact -->
							<article id="contact">
								<h2 class="major">联系{{ admin_name }}</h2>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<label for="name">姓名</label>
											<input type="text" name="name" id="name" />
										</div>
										<div class="field half">
											<label for="email">邮箱</label>
											<input type="text" name="email" id="email" />
										</div>
										<div class="field">
											<label for="message">留言</label>
											<textarea name="message" id="message" rows="4"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="发送消息" class="primary" /></li>
										<li><input type="reset" value="重置" /></li>
									</ul>
								</form>
<!--								<ul class="icons">-->
<!--									<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>-->
<!--									<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>-->
<!--									<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>-->
<!--									<li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>-->
<!--								</ul>-->
							</article>

						<!-- Elements -->
							<article id="elements">
								<h2 class="major">Elements</h2>

								<section>
									<h3 class="major">Text</h3>
									<p>This is <b>bold</b> and this is <strong>strong</strong>. This is <i>italic</i> and this is <em>emphasized</em>.
									This is <sup>superscript</sup> text and this is <sub>subscript</sub> text.
									This is <u>underlined</u> and this is code: <code>for (;;) { ... }</code>. Finally, <a href="#">this is a link</a>.</p>
									<hr />
									<h2>Heading Level 2</h2>
									<h3>Heading Level 3</h3>
									<h4>Heading Level 4</h4>
									<h5>Heading Level 5</h5>
									<h6>Heading Level 6</h6>
									<hr />
									<h4>Blockquote</h4>
									<blockquote>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan faucibus. Vestibulum ante ipsum primis in faucibus lorem ipsum dolor sit amet nullam adipiscing eu felis.</blockquote>
									<h4>Preformatted</h4>
									<pre><code>i = 0;

while (!deck.isInOrder()) {
    print 'Iteration ' + i;
    deck.shuffle();
    i++;
}

print 'It took ' + i + ' iterations to sort the deck.';</code></pre>
								</section>

								<section>
									<h3 class="major">Lists</h3>

									<h4>Unordered</h4>
									<ul>
										<li>Dolor pulvinar etiam.</li>
										<li>Sagittis adipiscing.</li>
										<li>Felis enim feugiat.</li>
									</ul>

									<h4>Alternate</h4>
									<ul class="alt">
										<li>Dolor pulvinar etiam.</li>
										<li>Sagittis adipiscing.</li>
										<li>Felis enim feugiat.</li>
									</ul>

									<h4>Ordered</h4>
									<ol>
										<li>Dolor pulvinar etiam.</li>
										<li>Etiam vel felis viverra.</li>
										<li>Felis enim feugiat.</li>
										<li>Dolor pulvinar etiam.</li>
										<li>Etiam vel felis lorem.</li>
										<li>Felis enim et feugiat.</li>
									</ol>
									<h4>Icons</h4>
									<ul class="icons">
										<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
										<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
										<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
										<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
									</ul>

									<h4>Actions</h4>
									<ul class="actions">
										<li><a href="#" class="button primary">Default</a></li>
										<li><a href="#" class="button">Default</a></li>
									</ul>
									<ul class="actions stacked">
										<li><a href="#" class="button primary">Default</a></li>
										<li><a href="#" class="button">Default</a></li>
									</ul>
								</section>

								<section>
									<h3 class="major">Table</h3>
									<h4>Default</h4>
									<div class="table-wrapper">
										<table>
											<thead>
												<tr>
													<th>Name</th>
													<th>Description</th>
													<th>Price</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>Item One</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Two</td>
													<td>Vis ac commodo adipiscing arcu aliquet.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Three</td>
													<td> Morbi faucibus arcu accumsan lorem.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Four</td>
													<td>Vitae integer tempus condimentum.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Five</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
											</tbody>
											<tfoot>
												<tr>
													<td colspan="2"></td>
													<td>100.00</td>
												</tr>
											</tfoot>
										</table>
									</div><div class="tlinks">Collect from <a href="http://www.cssmoban.com/"  title="网站模板">网站模板</a></div>
	
									<h4>Alternate</h4>
									<div class="table-wrapper">
										<table class="alt">
											<thead>
												<tr>
													<th>Name</th>
													<th>Description</th>
													<th>Price</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>Item One</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Two</td>
													<td>Vis ac commodo adipiscing arcu aliquet.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Three</td>
													<td> Morbi faucibus arcu accumsan lorem.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Four</td>
													<td>Vitae integer tempus condimentum.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Five</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
											</tbody>
											<tfoot>
												<tr>
													<td colspan="2"></td>
													<td>100.00</td>
												</tr>
											</tfoot>
										</table>
									</div>
								</section>

								<section>
									<h3 class="major">Buttons</h3>
									<ul class="actions">
										<li><a href="#" class="button primary">Primary</a></li>
										<li><a href="#" class="button">Default</a></li>
									</ul>
									<ul class="actions">
										<li><a href="#" class="button">Default</a></li>
										<li><a href="#" class="button small">Small</a></li>
									</ul>
									<ul class="actions">
										<li><a href="#" class="button primary icon solid fa-download">Icon</a></li>
										<li><a href="#" class="button icon solid fa-download">Icon</a></li>
									</ul>
									<ul class="actions">
										<li><span class="button primary disabled">Disabled</span></li>
										<li><span class="button disabled">Disabled</span></li>
									</ul>
								</section>

								<section>
									<h3 class="major">Form</h3>
									<form method="post" action="#">
										<div class="fields">
											<div class="field half">
												<label for="demo-name">Name</label>
												<input type="text" name="demo-name" id="demo-name" value="" placeholder="Jane Doe" />
											</div>
											<div class="field half">
												<label for="demo-email">Email</label>
												<input type="email" name="demo-email" id="demo-email" value="" placeholder="jane@abc.com" />
											</div>
											<div class="field">
												<label for="demo-category">Category</label>
												<select name="demo-category" id="demo-category">
													<option value="">-</option>
													<option value="1">Manufacturing</option>
													<option value="1">Shipping</option>
													<option value="1">Administration</option>
													<option value="1">Human Resources</option>
												</select>
											</div>
											<div class="field half">
												<input type="radio" id="demo-priority-low" name="demo-priority" checked>
												<label for="demo-priority-low">Low</label>
											</div>
											<div class="field half">
												<input type="radio" id="demo-priority-high" name="demo-priority">
												<label for="demo-priority-high">High</label>
											</div>
											<div class="field half">
												<input type="checkbox" id="demo-copy" name="demo-copy">
												<label for="demo-copy">Email me a copy</label>
											</div>
											<div class="field half">
												<input type="checkbox" id="demo-human" name="demo-human" checked>
												<label for="demo-human">Not a robot</label>
											</div>
											<div class="field">
												<label for="demo-message">Message</label>
												<textarea name="demo-message" id="demo-message" placeholder="Enter your message" rows="6"></textarea>
											</div>
										</div>
										<ul class="actions">
											<li><input type="submit" value="Send Message" class="primary" /></li>
											<li><input type="reset" value="Reset" /></li>
										</ul>
									</form>
								</section>

							</article>

					</div>

				<!-- Footer -->
					<footer id="footer">
						<p class="copyright">&copy; 鲁ICP备20006771号 </p>
					</footer>

			</div>

		<!-- BG -->
			<div id="bg"></div>
		<!-- Scripts -->
			<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}" charset="utf-8"></script>
			<script src="{{ url_for('static', filename='assets/js/browser.min.js') }}" charset="utf-8"></script>
			<script src="{{ url_for('static', filename='assets/js/breakpoints.min.js') }}" charset="utf-8"></script>
			<script src="{{ url_for('static', filename='assets/js/util.js') }}" charset="utf-8"></script>
			<script src="{{ url_for('static', filename='assets/js/main.js') }}" charset="utf-8"></script>
	</body>
</html>

app/user/templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
<meta charset="utf-8">
<title>欢迎加入</title>
<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/style_for_login.css') }}">
</head>

<body>
    <div class="content">
        <div class="form sign-in">
            <form action="{{ url_for('user.log_in_success') }}" method="post">
            <h2>欢迎回来</h2>
            <label>
                <span>邮箱</span>
                <input type="email" name="email" />
            </label>
            <label>
                <span>密码</span>
                <input type="password" name="password" />
            </label>
            <p class="forgot-pass"><a href="javascript:">忘记密码？</a></p>
            <button type="submit" class="submit">登 录</button>
<!--            <button type="button" class="fb-btn">使用 <span>facebook</span> 帐号登录</button>-->
            </form>
        </div>
        <div class="sub-cont">
            <div class="img">
                <div class="img__text m--up">
                    <h2>还未注册？</h2>
                    <p>立即注册，拥有自己的博客账号！</p>
                </div>
                <div class="img__text m--in">
                    <h2>已有帐号？</h2>
                    <p>有帐号就登录吧，好久不见了！</p>
                </div>
                <div class="img__btn">
                    <span class="m--up">注 册</span>
                    <span class="m--in">登 录</span>
                </div>
            </div>
            <div class="form sign-up">
                <form action="{{ url_for('user.log_in_success') }}" method="get">
                <h2>立即注册</h2>
                <label>
                    <span>用户名</span>
                    <input type="text" name="user_name" />
                </label>
                <label>
                    <span>邮箱</span>
                    <input type="email" name="email" />
                </label>
                <label>
                    <span>密码</span>
                    <input type="password" name="password" />
                </label>
                <button type="submit" class="submit">注 册</button>
                </form>
<!--                <button type="button" class="fb-btn">使用 <span>facebook</span> 帐号注册</button>-->
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='assets/js/script.js') }}"></script>
	
	<div style="text-align:center;">
</div>
</body>

</html>

app/user/templates/user_form.html
<!DOCTYPE HTML>
<html>
<head>
<title>Flat Flash Contact Form Responsive Widget Template | Home :: w3layouts</title>
<link href="{{ url_for('static', filename='assets/css/style_for_form.css') }}" rel="stylesheet" type="text/css" media="all"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="keywords" content="Flat Flash Contact Form  Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<!--web-fonts-->
<link href='//fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
<!--web-fonts-->
</head>
<body>
		<!---header--->
		<div class="header">
			<h1>Flash Contact Form</h1>
		</div>
		<!---header--->
		<!---main--->
			<div class="main">
				<div class="main-section">
				<div class="login-form">
					<h2>注册成功！清填写基本信息！</h2>
					<p>博客用户基本信息</p>
						<span></span>
					<form action="{{ url_for('user.user_form') }}" method="post">
						{{ forms.csrf_token }}
						{% for form in forms %}
							<h4> {% if form.label.text == "CSRF Token" %}

								  {% else %}
               						 {{ form.label }}
               						 {{ form }}
								<span style="color: red;">{{ form.errors.0 }}</span>

            					{% endif %}
							</h4>
						{% endfor %}
<!--						<h4>your name</h4>-->
<!--						<input type="text" class="user" placeholder="Johne" required="">-->
<!--						<h4>your phone number</h4>-->
<!--						<input type="text" class="phone" placeholder="0900.234.145678" >-->
<!--						<h4>your email address</h4>-->
<!--						<input type="text" class="email" placeholder="Example@mail.com">-->
<!--						<h4>your message</h4>-->
<!--						<textarea class="mess" placeholder="Message"></textarea>-->
						<input type="submit" value="提交">
					</form>
				</div>
				</div>
			</div>
			<div class="footer">
			<p>&copy 2016 Flat Flash Contact Form . All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
		</div>

		<!---main--->
</body>
</html>